import { Perfume, FragranceFamily, Usage } from './types';

export const PERFUMES: Perfume[] = [
  {
    id: 1,
    name: "aurélique Lignum Lux",
    tagline: "Elegance you can feel, confidence you can wear.",
    mainChords: [FragranceFamily.Citrus, FragranceFamily.Fresh],
    topNotes: ["Lavender", "Pink Pepper", "Aldehyde"],
    heartNotes: ["Linalool", "Jasmine", "Violet"],
    baseNotes: ["Musk", "Cedarwood Virginia", "Woody"],
    usage: Usage.AllSeason,
    price: 195000,
    isBestSeller: true,
    image: "https://lh3.googleusercontent.com/pw/AP1GczNKSNxZg-Q-nr8UinSzFfcA27teANrL8aO2RR83BL84Xkd0TkEqhMcXq4aII0HM1Jy6xt9RgC_CBxqOKVMWWVTP7RdYSeNfcKFo2zVquMV1SLk1P8_rAlikPXCoc5G9Lczg3OFPjLz3WFrSnBOBcas=w832-h1248-s-no-gm?authuser=0"
  },
  {
    id: 2,
    name: "aurélique Dominus",
    tagline: "A Bold Signature for the Modern Gentleman.",
    mainChords: [FragranceFamily.Aromatic, FragranceFamily.Spicy],
    topNotes: ["Pink Pepper", "Lavender", "Eucalyptol"],
    heartNotes: ["Rose", "Tobacco", "Violet"],
    baseNotes: ["Amber Accord", "Patchouli", "Ambroxan"],
    usage: Usage.Night,
    price: 195000,
    isBestSeller: false,
    image: "https://lh3.googleusercontent.com/pw/AP1GczPgKZfEhn9eqGAVBBNoFqIFSfhV8n4m52Qig7ZJIBKL91BLEMZ963HOebPsTS_pF95gOJT5f-xyPy2Q12i7uD6xFmFAGOe_MoRNUlHq-JoLOvq3uVgTjqsZH27xsjLVItkYgtcMSLRZJCTiiJgzRkE=w1024-h1536-s-no-gm?authuser=0"
  },
  {
    id: 3,
    name: "Bvlgary Aqua",
    tagline: "The essence of Mediterranean water.",
    mainChords: [FragranceFamily.Fresh, FragranceFamily.Citrus],
    topNotes: ["Mandarin", "Petitgrain"],
    heartNotes: ["Seaweed", "Lavender", "Cotton Flower"],
    baseNotes: ["Cedar", "Amber", "Clary Sage"],
    usage: Usage.Day,
    price: 1350000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/3/400/600"
  },
  {
    id: 4,
    name: "Terre D'Hermes",
    tagline: "Earthy elegance under the sky.",
    mainChords: [FragranceFamily.Woody, FragranceFamily.Spicy],
    topNotes: ["Orange", "Grapefruit"],
    heartNotes: ["Pepper", "Pelargonium"],
    baseNotes: ["Cedar", "Patchouli", "Vetiver"],
    usage: Usage.AllSeason,
    price: 2100000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/4/400/600"
  },
  {
    id: 5,
    name: "JPG SO Scandal",
    tagline: "A scandalous floral delight.",
    mainChords: [FragranceFamily.Floral, FragranceFamily.Oriental],
    topNotes: ["Raspberry", "Orange Blossom"],
    heartNotes: ["Tuberose", "Jasmine"],
    baseNotes: ["Sandalwood", "Ambroxan"],
    usage: Usage.SpecialOccasion,
    price: 1850000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/5/400/600"
  },
  {
    id: 6,
    name: "JPG Ultra Male",
    tagline: "The ultimate seductive power.",
    mainChords: [FragranceFamily.Spicy, FragranceFamily.Oriental],
    topNotes: ["Pear", "Lavender", "Mint"],
    heartNotes: ["Cinnamon", "Clary Sage"],
    baseNotes: ["Vanilla", "Amber", "Cedar"],
    usage: Usage.Night,
    price: 1700000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/6/400/600"
  },
  {
    id: 7,
    name: "Issey Miyake Man",
    tagline: "Minimalist aquatic elegance.",
    mainChords: [FragranceFamily.Fresh, FragranceFamily.Aromatic],
    topNotes: ["Yuzu", "Cypress", "Coriander"],
    heartNotes: ["Nutmeg", "Saffron"],
    baseNotes: ["Vetiver", "Musk", "Amber"],
    usage: Usage.Day,
    price: 1500000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/7/400/600"
  },
  {
    id: 8,
    name: "LV Les Sables Rose",
    tagline: "Rose and oud in the desert wind.",
    mainChords: [FragranceFamily.Oriental, FragranceFamily.Floral],
    topNotes: ["Rose"],
    heartNotes: ["Ambergris"],
    baseNotes: ["Oud"],
    usage: Usage.SpecialOccasion,
    price: 5800000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/8/400/600"
  },
  {
    id: 9,
    name: "Angel Mugler",
    tagline: "Sweet gourmand starlight.",
    mainChords: [FragranceFamily.Oriental, FragranceFamily.Floral],
    topNotes: ["Cotton Candy", "Coconut", "Mandarin"],
    heartNotes: ["Honey", "Jasmine", "Berries"],
    baseNotes: ["Chocolate", "Caramel", "Patchouli"],
    usage: Usage.Night,
    price: 1600000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/9/400/600"
  },
  {
    id: 10,
    name: "Acqua Di Gio Man",
    tagline: "An eternal Mediterranean classic.",
    mainChords: [FragranceFamily.Citrus, FragranceFamily.Fresh],
    topNotes: ["Lime", "Lemon", "Jasmine"],
    heartNotes: ["Coriander", "Rosemary"],
    baseNotes: ["Oakmoss", "Cedar", "Patchouli"],
    usage: Usage.AllSeason,
    price: 1450000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/10/400/600"
  },
  {
    id: 11,
    name: "Mancera Cedrat Boise",
    tagline: "Fruity citrus with woody depth.",
    mainChords: [FragranceFamily.Citrus, FragranceFamily.Woody],
    topNotes: ["Sicilian Lemon", "Black Currant"],
    heartNotes: ["Jasmine", "Patchouli"],
    baseNotes: ["Cedar", "Leather", "Vanilla"],
    usage: Usage.AllSeason,
    price: 2200000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/11/400/600"
  },
  {
    id: 12,
    name: "Initio Oud For Greatness",
    tagline: "Majestic oud power.",
    mainChords: [FragranceFamily.Oriental, FragranceFamily.Spicy],
    topNotes: ["Saffron", "Nutmeg", "Lavender"],
    heartNotes: ["Agarwood", "Patchouli"],
    baseNotes: ["Musk"],
    usage: Usage.SpecialOccasion,
    price: 4500000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/12/400/600"
  },
  {
    id: 13,
    name: "Initio Psychedelic Love",
    tagline: "A hypnotic white floral addiction.",
    mainChords: [FragranceFamily.Floral, FragranceFamily.Oriental],
    topNotes: ["Bergamot", "Rose"],
    heartNotes: ["Heliotrope", "Jasmine"],
    baseNotes: ["Sandalwood", "Musk"],
    usage: Usage.Night,
    price: 4200000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/13/400/600"
  },
  {
    id: 14,
    name: "Spicebomb",
    tagline: "An explosion of spices.",
    mainChords: [FragranceFamily.Spicy, FragranceFamily.Woody],
    topNotes: ["Pink Pepper", "Bergamot", "Grapefruit"],
    heartNotes: ["Cinnamon", "Saffron"],
    baseNotes: ["Leather", "Tobacco", "Vetiver"],
    usage: Usage.Night,
    price: 1900000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/14/400/600"
  },
  {
    id: 15,
    name: "Davidoff Coolwater",
    tagline: "A cool wave of freshness.",
    mainChords: [FragranceFamily.Fresh, FragranceFamily.Aromatic],
    topNotes: ["Mint", "Lavender", "Coriander"],
    heartNotes: ["Geranium", "Neroli"],
    baseNotes: ["Musk", "Cedar", "Amber"],
    usage: Usage.Day,
    price: 1150000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/15/400/600"
  },
  {
    id: 16,
    name: "D&G Light Blue",
    tagline: "Mediterranean sun in a bottle.",
    mainChords: [FragranceFamily.Citrus, FragranceFamily.Fresh],
    topNotes: ["Sicilian Lemon", "Apple"],
    heartNotes: ["Jasmine", "Rose"],
    baseNotes: ["Cedarwood", "Amber", "Musk"],
    usage: Usage.Day,
    price: 1600000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/16/400/600"
  },
  {
    id: 17,
    name: "Creed Aventus",
    tagline: "The king of modern chypres.",
    mainChords: [FragranceFamily.Woody, FragranceFamily.Fruity],
    topNotes: ["Pineapple", "Blackcurrant", "Apple"],
    heartNotes: ["Birch", "Patchouli", "Rose"],
    baseNotes: ["Musk", "Oakmoss", "Ambergris"],
    usage: Usage.AllSeason,
    price: 6500000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/17/400/600"
  },
  {
    id: 18,
    name: "Creed Silver Mountain Water",
    tagline: "Fresh alpine purity.",
    mainChords: [FragranceFamily.Fresh, FragranceFamily.Citrus],
    topNotes: ["Bergamot", "Mandarin"],
    heartNotes: ["Green Tea", "Blackcurrant"],
    baseNotes: ["Musk", "Sandalwood"],
    usage: Usage.Day,
    price: 6300000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/18/400/600"
  },
  {
    id: 19,
    name: "Versace Eros",
    tagline: "Passionate Greek god energy.",
    mainChords: [FragranceFamily.Aromatic, FragranceFamily.Fresh],
    topNotes: ["Mint", "Green Apple", "Lemon"],
    heartNotes: ["Tonka Bean", "Geranium"],
    baseNotes: ["Vanilla", "Vetiver", "Cedarwood"],
    usage: Usage.Night,
    price: 1850000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/19/400/600"
  },
  {
    id: 20,
    name: "Selena Gomez",
    tagline: "Playful fruity sweetness.",
    mainChords: [FragranceFamily.Floral, FragranceFamily.Fruity],
    topNotes: ["Peach", "Raspberry", "Pineapple"],
    heartNotes: ["Freesia", "Musk"],
    baseNotes: ["Vanilla", "Amber"],
    usage: Usage.Day,
    price: 900000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/20/400/600"
  },
  {
    id: 21,
    name: "Prada Candy Kiss",
    tagline: "A kiss of sweet addiction.",
    mainChords: [FragranceFamily.Oriental, FragranceFamily.Floral],
    topNotes: ["Musk"],
    heartNotes: ["Orange Blossom"],
    baseNotes: ["Vanilla"],
    usage: Usage.Night,
    price: 1700000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/21/400/600"
  },
  {
    id: 22,
    name: "Marc Jacob Daisy",
    tagline: "Youthful floral charm.",
    mainChords: [FragranceFamily.Floral, FragranceFamily.Fresh],
    topNotes: ["Strawberry", "Violet Leaf"],
    heartNotes: ["Gardenia", "Jasmine"],
    baseNotes: ["Musk", "Vanilla", "White Woods"],
    usage: Usage.Day,
    price: 1500000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/22/400/600"
  },
  {
    id: 23,
    name: "Issey Miyake Woman",
    tagline: "A delicate floral aquatic harmony.",
    mainChords: [FragranceFamily.Floral, FragranceFamily.Fresh],
    topNotes: ["Lotus", "Rose Water"],
    heartNotes: ["Lily", "Peony"],
    baseNotes: ["Cedar", "Amber", "Musk"],
    usage: Usage.Day,
    price: 1400000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/23/400/600"
  },
  {
    id: 24,
    name: "Baccarat Rouge",
    tagline: "Crystalline sweetness in the air.",
    mainChords: [FragranceFamily.Oriental, FragranceFamily.Aromatic],
    topNotes: ["Saffron", "Jasmine"],
    heartNotes: ["Amberwood", "Ambergris"],
    baseNotes: ["Fir Resin", "Cedar"],
    usage: Usage.SpecialOccasion,
    price: 7500000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/24/400/600"
  },
  {
    id: 25,
    name: "Prada Paradox",
    tagline: "The paradox of modern femininity.",
    mainChords: [FragranceFamily.Floral, FragranceFamily.Oriental],
    topNotes: ["Pear", "Tangerine"],
    heartNotes: ["Neroli", "Jasmine"],
    baseNotes: ["Amber", "Musk", "Vanilla"],
    usage: Usage.AllSeason,
    price: 1900000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/25/400/600"
  },
  {
    id: 26,
    name: "Bleu De Chanel",
    tagline: "Timeless woody aromatic elegance.",
    mainChords: [FragranceFamily.Woody, FragranceFamily.Aromatic],
    topNotes: ["Lemon", "Mint", "Pink Pepper"],
    heartNotes: ["Ginger", "Nutmeg", "Jasmine"],
    baseNotes: ["Sandalwood", "Patchouli", "Cedar"],
    usage: Usage.AllSeason,
    price: 2600000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/26/400/600"
  },
  {
    id: 27,
    name: "Dior Jadore",
    tagline: "Golden floral radiance.",
    mainChords: [FragranceFamily.Floral, FragranceFamily.Oriental],
    topNotes: ["Pear", "Peach", "Bergamot"],
    heartNotes: ["Magnolia", "Rose", "Jasmine"],
    baseNotes: ["Vanilla", "Cedar", "Musk"],
    usage: Usage.SpecialOccasion,
    price: 2500000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/27/400/600"
  },
  {
    id: 28,
    name: "Miss Dior",
    tagline: "Romantic elegance reborn.",
    mainChords: [FragranceFamily.Floral, FragranceFamily.Fresh],
    topNotes: ["Blood Orange", "Mandarin"],
    heartNotes: ["Turkish Rose", "Jasmine"],
    baseNotes: ["Patchouli", "Amber", "Musk"],
    usage: Usage.AllSeason,
    price: 2400000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/28/400/600"
  },
  {
    id: 29,
    name: "Britney Spears Fantasy",
    tagline: "A playful fruity gourmand.",
    mainChords: [FragranceFamily.Floral, FragranceFamily.Oriental],
    topNotes: ["Kiwi", "Lychee", "Quince"],
    heartNotes: ["Cupcake Accord", "Jasmine"],
    baseNotes: ["Musk", "Orris Root", "Amber"],
    usage: Usage.Night,
    price: 800000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/29/400/600"
  },
  {
    id: 30,
    name: "Chanel COCO",
    tagline: "Classic oriental sophistication.",
    mainChords: [FragranceFamily.Oriental, FragranceFamily.Spicy],
    topNotes: ["Mandarin", "Coriander"],
    heartNotes: ["Rose", "Orange Blossom"],
    baseNotes: ["Amber", "Sandalwood", "Tonka Bean"],
    usage: Usage.SpecialOccasion,
    price: 2900000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/30/400/600"
  },
  {
    id: 31,
    name: "YSL Libre",
    tagline: "Freedom in a floral breeze.",
    mainChords: [FragranceFamily.Floral, FragranceFamily.Aromatic],
    topNotes: ["Lavender", "Mandarin", "Black Currant"],
    heartNotes: ["Orange Blossom", "Jasmine"],
    baseNotes: ["Cedarwood", "Ambergris", "Vanilla"],
    usage: Usage.AllSeason,
    price: 2100000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/31/400/600"
  },
  {
    id: 32,
    name: "YSL Black Opium",
    tagline: "The addictive coffee floral.",
    mainChords: [FragranceFamily.Oriental, FragranceFamily.Floral],
    topNotes: ["Pear", "Pink Pepper", "Orange Blossom"],
    heartNotes: ["Coffee", "Jasmine"],
    baseNotes: ["Vanilla", "Cedarwood", "Patchouli"],
    usage: Usage.Night,
    price: 1900000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/32/400/600"
  },
  {
    id: 33,
    name: "YSL Y",
    tagline: "Modern masculinity with fresh boldness.",
    mainChords: [FragranceFamily.Fresh, FragranceFamily.Aromatic],
    topNotes: ["Aldehydes", "Bergamot", "Ginger"],
    heartNotes: ["Sage", "Juniper Berries", "Geranium"],
    baseNotes: ["Ambergris", "Cedarwood", "Tonka Bean"],
    usage: Usage.AllSeason,
    price: 2200000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/33/400/600"
  },
  {
    id: 34,
    name: "Dior Sauvage",
    tagline: "Raw freshness and bold strength.",
    mainChords: [FragranceFamily.Aromatic, FragranceFamily.Spicy],
    topNotes: ["Calabrian Bergamot", "Pepper"],
    heartNotes: ["Lavender", "Sichuan Pepper", "Pink Pepper"],
    baseNotes: ["Ambroxan", "Cedar", "Labdanum"],
    usage: Usage.AllSeason,
    price: 2400000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/34/400/600"
  },
 {
    id: 35,
    name: "CK One",
    tagline: "A timeless unisex freshness.",
    mainChords: [FragranceFamily.Citrus, FragranceFamily.Fresh],
    topNotes: ["Pineapple", "Mandarin Orange", "Papaya"],
    heartNotes: ["Nutmeg", "Violet", "Rose"],
    baseNotes: ["Green Tea", "Amber", "Musk"],
    usage: Usage.AllSeason,
    price: 175000,
    isBestSeller: true,
    image: "https://picsum.photos/seed/1/400/600"
  },
  id: 36,
    name: "CK Free",
    tagline: "Freedom bottled in freshness.",
    mainChords: [FragranceFamily.Aromatic, FragranceFamily.Fresh],
    topNotes: ["Absinthe", "Jackfruit", "Star Anise"],
    heartNotes: ["Coffee", "Tobacco", "Leather"],
    baseNotes: ["Oak", "Cedarwood", "Patchouli"],
    usage: Usage.Day,
    price: 1100000,
    isBestSeller: false,
    image: "https://picsum.photos/seed/2/400/600"
  }
]